/**
 * Public exercise data for SEO exercise pages.
 *
 * Only includes long-tail exercises where we have a realistic chance of ranking.
 * Popular exercises (bench press, deadlift, squat, pushup, pull-up, bicep curl, etc.)
 * are dominated by bodybuilding.com, nerdfitness, etc. — we skip those.
 *
 * Each exercise has: slug, name, meta (title/description), intro copy, form cues,
 * common mistakes, muscles, equipment, difficulty, video, and whether PushUp Pro
 * can camera-track it.
 */

export const exercises = [
  // === BODYWEIGHT / CORE (high search, less competition) ===
  {
    slug: 'dead-bug',
    name: 'Dead Bug',
    title: 'How to Do the Dead Bug Exercise (Form Guide + Video)',
    description: 'The dead bug builds core stability without stressing your back. Learn proper dead bug form, common mistakes, and how AI tracks your reps.',
    primaryMuscle: 'core',
    muscleGroups: ['core'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'x-BStnplCYg',
    intro: 'The dead bug is one of the best core exercises most people have never tried. Unlike crunches and sit-ups that repeatedly flex your spine, the dead bug teaches your core to resist movement — which is how your abs actually work in real life. Physical therapists prescribe it for back pain because it strengthens your core without putting any stress on your lumbar spine.',
    formCues: [
      'Lie on your back with arms reaching toward the ceiling',
      'Bend knees to 90 degrees — shins parallel to the floor',
      'Press your lower back flat into the ground (no gap)',
      'Slowly extend one arm overhead and the opposite leg out',
      'Return to start and repeat on the other side',
    ],
    commonMistakes: [
      'Lower back arching off the floor — keep it pressed down the entire time',
      'Moving too fast — slow and controlled is the whole point',
      'Holding your breath — exhale as you extend, inhale as you return',
    ],
  },
  {
    slug: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    title: 'How to Do the Hollow Body Hold (Gymnast Core Exercise)',
    description: 'The hollow body hold is the foundation of gymnastics core strength. Learn proper form, progressions, and how long you should actually hold it.',
    primaryMuscle: 'core',
    muscleGroups: ['core', 'shoulders'],
    equipment: ['none'],
    difficulty: 'intermediate',
    trackingMode: 'hold',
    aiTracked: true,
    videoId: 'Mjeur54Z0wI',
    intro: 'The hollow body hold is the single most important core exercise in gymnastics — and one of the most underrated in general fitness. It trains your entire anterior chain (abs, hip flexors, quads) to work as one unit. If you can hold a solid hollow body for 30 seconds, you have real core strength. Most people who claim strong abs can barely manage 10 seconds with proper form.',
    formCues: [
      'Lie flat on your back, arms overhead, legs straight',
      'Press your lower back into the floor — eliminate the gap completely',
      'Lift arms, head, shoulders, and legs a few inches off the ground',
      'Your body should look like a banana — curved, not flat',
      'Hold while breathing — don\'t hold your breath',
    ],
    commonMistakes: [
      'Lower back lifting off the floor — this means your legs are too low or you\'re not strong enough yet',
      'Bending knees or arms to make it easier — regress by tucking knees instead',
      'Head dropping back — keep chin slightly tucked, looking at your toes',
    ],
  },
  {
    slug: 'v-up',
    name: 'V-Up',
    title: 'How to Do V-Ups (Proper Form + Common Mistakes)',
    description: 'V-ups are an advanced core exercise that hits your entire abdominal wall. Learn proper technique, easier progressions, and mistakes to avoid.',
    primaryMuscle: 'core',
    muscleGroups: ['core'],
    equipment: ['none'],
    difficulty: 'intermediate',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'BNIPC_HaXWQ',
    intro: 'The V-up combines a crunch and a leg raise into one explosive movement. It targets your rectus abdominis (the six-pack muscles) through their full range of motion — something most ab exercises fail to do. V-ups are tough. If you can do 15 with good form, your core is legitimately strong.',
    formCues: [
      'Lie flat on your back with arms extended overhead',
      'Simultaneously lift your legs and torso to form a V shape',
      'Reach your hands toward your toes at the top',
      'Lower back down with control — don\'t just drop',
      'Keep legs as straight as possible throughout',
    ],
    commonMistakes: [
      'Using momentum instead of muscle — slow down the movement',
      'Bending knees excessively — keep legs as straight as you can',
      'Not reaching full range — your hands should get close to your toes',
    ],
  },
  {
    slug: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    title: 'How to Do Ab Wheel Rollouts (Without Hurting Your Back)',
    description: 'Ab wheel rollouts are one of the hardest core exercises. Learn safe form, progressions from knees to standing, and how to protect your lower back.',
    primaryMuscle: 'core',
    muscleGroups: ['core', 'shoulders'],
    equipment: ['ab wheel'],
    difficulty: 'advanced',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'MinlHnG7j4k',
    intro: 'The ab wheel rollout is a humbling exercise. It looks simple — roll out, roll back. But it demands extreme anti-extension strength from your core, and most people\'s lower backs give out long before their abs do. Done right, it\'s one of the most effective core exercises that exist. Done wrong, it\'s a fast track to back pain.',
    formCues: [
      'Start on your knees with the wheel in front of you',
      'Brace your core hard — squeeze abs and glutes',
      'Roll forward slowly, keeping your hips extended (not sitting back)',
      'Go only as far as you can without your lower back arching',
      'Pull back by driving your hands into the wheel and flexing your abs',
    ],
    commonMistakes: [
      'Lower back sagging at full extension — you went too far, shorten the range',
      'Hips sitting back on the return (the "cheater rollout") — keep hips pushed forward',
      'Going too fast — this is a slow, controlled movement',
    ],
  },
  {
    slug: 'side-plank',
    name: 'Side Plank',
    title: 'How to Do Side Planks (Build Oblique Strength That Matters)',
    description: 'Side planks target your obliques and lateral core. Learn proper side plank form, common mistakes, and progressions from beginner to advanced.',
    primaryMuscle: 'core',
    muscleGroups: ['core', 'shoulders'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'hold',
    aiTracked: true,
    videoId: 'wP7xBF-LZxs',
    intro: 'Side planks are the most effective oblique exercise you can do — and one of the most commonly butchered. While regular planks train anti-extension (resisting your back from arching), side planks train anti-lateral-flexion (resisting sideways bending). This is critical for spine health, athletic performance, and actually building a strong midsection.',
    formCues: [
      'Lie on your side with elbow directly under shoulder',
      'Stack feet or stagger them (staggering is easier)',
      'Lift hips until body forms a straight line from head to feet',
      'Top arm can rest on your side or reach toward the ceiling',
      'Hold while breathing steadily — don\'t collapse between breaths',
    ],
    commonMistakes: [
      'Hips sagging toward the floor — squeeze your obliques harder',
      'Rolling forward or backward — your body should be in one plane',
      'Elbow too far forward or back — keep it directly under your shoulder',
    ],
  },

  // === GLUTES / LOWER BODY (long-tail, less competition) ===
  {
    slug: 'hip-thrust',
    name: 'Hip Thrust',
    title: 'How to Do Hip Thrusts (The Best Glute Exercise, Period)',
    description: 'Hip thrusts activate your glutes more than any other exercise. Learn proper setup, form cues, and mistakes that kill your results.',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes', 'hamstrings', 'core'],
    equipment: ['bench', 'barbell'],
    difficulty: 'intermediate',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: '8BPi7X21BhA',
    intro: 'The hip thrust is the single best exercise for glute development. EMG studies consistently show it activates the glutes more than squats, deadlifts, or lunges. If you want stronger, bigger glutes — for aesthetics, athletics, or back pain prevention — hip thrusts should be in your program.',
    formCues: [
      'Sit on the floor with your upper back against a bench',
      'Roll a barbell over your hips (use a pad for comfort)',
      'Feet flat, shoulder-width apart, about 12 inches from your butt',
      'Drive through your heels and squeeze glutes to lift hips',
      'At the top, your shins should be vertical and torso parallel to the floor',
    ],
    commonMistakes: [
      'Hyperextending the lower back at the top — stop when hips are level with shoulders',
      'Feet too far forward — shins should be vertical at lockout',
      'Pushing through toes instead of heels — you\'ll feel it in your quads, not glutes',
    ],
  },
  {
    slug: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    title: 'How to Do Bulgarian Split Squats (Setup, Form, Progressions)',
    description: 'Bulgarian split squats build single-leg strength and fix muscle imbalances. Learn proper foot placement, depth, and how to stop wobbling.',
    primaryMuscle: 'quads',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['bench'],
    difficulty: 'intermediate',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'Q20qIs79tJc',
    intro: 'The Bulgarian split squat is the exercise everyone loves to hate. It\'s awkward, it burns, and the balance challenge is humbling. But it\'s one of the most effective lower body exercises because it forces each leg to work independently — exposing and fixing the strength imbalances that bilateral squats hide.',
    formCues: [
      'Stand about 2 feet in front of a bench, one foot elevated behind you',
      'Most of your weight should be on the front foot',
      'Lower straight down until your back knee nearly touches the floor',
      'Front shin stays relatively vertical — knee tracks over toes',
      'Drive through the front foot to stand back up',
    ],
    commonMistakes: [
      'Standing too close to the bench — creates excessive knee travel and stress',
      'Leaning forward — stay upright, think "down" not "forward"',
      'Back foot doing too much work — it\'s just for balance, front leg does the work',
    ],
  },
  {
    slug: 'glute-bridge',
    name: 'Glute Bridge',
    title: 'How to Do Glute Bridges (Beginner Glute Activation Guide)',
    description: 'Glute bridges are the best starting point for building glute strength. Learn proper form, why your glutes might not be firing, and progressions.',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes', 'hamstrings', 'core'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'R6n608M3czU',
    intro: 'The glute bridge is where glute training starts. If you sit at a desk all day, your glutes are probably weak and underactive — a condition called "gluteal amnesia." Glute bridges wake them up. They\'re also one of the safest hip extension exercises, making them perfect for beginners and people recovering from back issues.',
    formCues: [
      'Lie on your back with knees bent, feet flat and hip-width apart',
      'Feet should be about 12 inches from your butt',
      'Drive through your heels and squeeze your glutes to lift hips',
      'At the top, your body forms a straight line from shoulders to knees',
      'Pause and squeeze at the top for 1-2 seconds, then lower with control',
    ],
    commonMistakes: [
      'Pushing hips too high — hyperextending the lower back instead of using glutes',
      'Feeling it in your hamstrings instead of glutes — move feet closer to your butt',
      'Not squeezing at the top — the pause is where the activation happens',
    ],
  },
  {
    slug: 'fire-hydrant',
    name: 'Fire Hydrant',
    title: 'How to Do Fire Hydrants (Glute Med Activation Exercise)',
    description: 'Fire hydrants target the gluteus medius — the side glute muscle most people neglect. Learn proper form and why this exercise prevents knee injuries.',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'BLx5wSzafxg',
    intro: 'The fire hydrant looks like a simple exercise — and it is. But it targets the gluteus medius (your side glute), which is one of the most neglected muscles in fitness. A weak glute med is the root cause of knee cave during squats, IT band syndrome in runners, and hip instability. If your knees collapse inward during squats, fire hydrants should be in your warm-up.',
    formCues: [
      'Start on all fours — hands under shoulders, knees under hips',
      'Keep your core tight and back flat',
      'Lift one knee out to the side, keeping the 90-degree bend',
      'Lift until your thigh is parallel to the floor (or as high as you can)',
      'Lower with control — don\'t just drop back down',
    ],
    commonMistakes: [
      'Rotating your torso to get the leg higher — keep your hips square',
      'Arching your lower back — brace your core throughout',
      'Moving too fast — slow and controlled activates the glute med more',
    ],
  },
  {
    slug: 'donkey-kick',
    name: 'Donkey Kick',
    title: 'How to Do Donkey Kicks (Glute Isolation Without Equipment)',
    description: 'Donkey kicks isolate your glute max with zero equipment. Learn how to actually feel it in your glutes instead of your lower back.',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'YoOlLusFMYU',
    intro: 'Donkey kicks isolate the gluteus maximus — the biggest muscle in your body — without any equipment. They\'re a staple in physical therapy and glute activation warm-ups because they teach your brain to fire your glutes independently. The catch: most people do them wrong and feel it in their lower back instead of their butt.',
    formCues: [
      'Start on all fours — hands under shoulders, knees under hips',
      'Keep your core braced and back flat throughout',
      'Drive one heel toward the ceiling, keeping the knee bent at 90 degrees',
      'Squeeze your glute hard at the top — don\'t just kick up',
      'Lower with control, stopping just before the knee touches the ground',
    ],
    commonMistakes: [
      'Arching the lower back to get the leg higher — keep your back flat and use less range',
      'Not squeezing the glute at the top — the squeeze IS the exercise',
      'Swinging the leg with momentum — slow and intentional wins',
    ],
  },
  {
    slug: 'nordic-curl',
    name: 'Nordic Curl',
    title: 'How to Do Nordic Curls (Hardest Hamstring Exercise)',
    description: 'Nordic curls are the gold standard for hamstring strength and injury prevention. Learn progressions from beginner to full nordic curl.',
    primaryMuscle: 'hamstrings',
    muscleGroups: ['hamstrings'],
    equipment: ['none'],
    difficulty: 'advanced',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: '1IIavrSbEvo',
    intro: 'The nordic curl is the single most effective hamstring exercise. Research consistently shows it reduces hamstring injury rates by 51-70% in athletes. It builds eccentric hamstring strength — the ability to control deceleration — which is exactly what prevents pulls and tears. Fair warning: the first time you try it, you will likely face-plant. That\'s normal.',
    formCues: [
      'Kneel on a pad with someone holding your ankles (or hook under something solid)',
      'Start upright with hips extended — squeeze glutes forward',
      'Slowly lower yourself toward the ground as far as you can control',
      'Resist gravity with your hamstrings — this is the hard part',
      'When you can\'t hold anymore, catch yourself with your hands and push back up',
    ],
    commonMistakes: [
      'Bending at the hips instead of keeping them extended — this turns it into a back exercise',
      'Dropping too fast — the slow eccentric lowering IS the exercise',
      'Skipping progressions — start with just the top 1/4 range and build up over weeks',
    ],
  },
  {
    slug: 'sissy-squat',
    name: 'Sissy Squat',
    title: 'How to Do Sissy Squats (The Forgotten Quad Exercise)',
    description: 'Sissy squats isolate your quads through extreme range of motion. Learn how to do them safely and why the name is misleading.',
    primaryMuscle: 'quads',
    muscleGroups: ['quads'],
    equipment: ['none'],
    difficulty: 'advanced',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'AYN-U5nZieY',
    intro: 'Don\'t let the name fool you — the sissy squat is brutally hard. Named after King Sisyphus from Greek mythology, it puts your quads through an extreme range of motion that most exercises can\'t touch. It\'s one of the few bodyweight movements that can genuinely build quad size and strength without any equipment.',
    formCues: [
      'Stand with feet hip-width apart, hold something for balance',
      'Rise up onto your toes',
      'Lean your torso back while bending your knees forward',
      'Lower until your knees point forward and torso leans way back',
      'Drive through your toes to return to standing',
    ],
    commonMistakes: [
      'Not going deep enough — the deep stretch is what makes this exercise effective',
      'Bending at the hips — keep your body in a straight line from knees to shoulders',
      'Skipping the eccentric — lower slowly for 3-4 seconds',
    ],
  },

  // === BACK / POSTERIOR CHAIN ===
  {
    slug: 'face-pull',
    name: 'Face Pull',
    title: 'How to Do Face Pulls (Fix Your Posture and Shoulders)',
    description: 'Face pulls strengthen your rear delts and rotator cuff — the muscles that fix rounded shoulders. Learn cable setup, form, and rep ranges.',
    primaryMuscle: 'rear delts',
    muscleGroups: ['shoulders', 'back'],
    equipment: ['cable machine', 'rope'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'qEyoBOpvqR4',
    intro: 'Face pulls are the most important exercise nobody does enough of. They strengthen your rear deltoids, rotator cuff, and mid-back — the exact muscles that prevent rounded shoulders, shoulder impingement, and the posture problems that come from too much pressing and sitting. If you bench press or sit at a desk, you need face pulls.',
    formCues: [
      'Set a cable to face height with a rope attachment',
      'Grab the rope with an overhand grip and step back',
      'Pull the rope toward your face, splitting it apart at the end',
      'Squeeze your shoulder blades together and externally rotate',
      'Your hands should end up beside your ears at the finish',
    ],
    commonMistakes: [
      'Using too much weight — this is a light, high-rep exercise (15-25 reps)',
      'Pulling to your chest instead of your face — keep the angle high',
      'Not splitting the rope apart — the external rotation at the end is the key part',
    ],
  },
  {
    slug: 'reverse-fly',
    name: 'Reverse Fly',
    title: 'How to Do Reverse Flyes (Rear Delt and Posture Exercise)',
    description: 'Reverse flyes target your rear delts and rhomboids. Learn proper form for dumbbell and cable variations, plus common mistakes.',
    primaryMuscle: 'rear delts',
    muscleGroups: ['shoulders', 'back'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: '-TKqxK7-ehc',
    intro: 'The reverse fly targets your rear deltoids and upper back muscles — the same group that face pulls hit, but with a different angle and load. If your shoulders round forward or you get shoulder pain from pressing, reverse flyes are a direct fix. They\'re simple, safe, and effective with light dumbbells.',
    formCues: [
      'Hinge forward at the hips, keeping your back flat',
      'Let dumbbells hang straight down with a slight elbow bend',
      'Raise arms out to the sides, squeezing your shoulder blades together',
      'Lead with your elbows, not your hands',
      'Lower with control — don\'t just drop the weight',
    ],
    commonMistakes: [
      'Using too much weight and swinging — go lighter than you think',
      'Rounding your upper back — maintain a flat back and proud chest',
      'Not squeezing at the top — the contraction is the point',
    ],
  },
  {
    slug: 'superman',
    name: 'Superman',
    title: 'How to Do the Superman Exercise (Lower Back Strengthener)',
    description: 'The superman exercise strengthens your lower back, glutes, and posterior chain with zero equipment. Learn proper form and variations.',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'w5WIZ-rY9NQ',
    intro: 'The superman is a bodyweight exercise that targets your lower back, glutes, and posterior chain. It\'s the opposite of a crunch — instead of flexing your spine forward, you extend it backward. This makes it one of the best exercises for people with weak lower backs, desk workers who need to counteract slouching, and anyone building a balanced core.',
    formCues: [
      'Lie face down with arms extended overhead and legs straight',
      'Simultaneously lift your arms, chest, and legs off the floor',
      'Squeeze your glutes and lower back at the top',
      'Hold for 1-2 seconds, then lower with control',
      'Keep your neck neutral — look at the floor, not forward',
    ],
    commonMistakes: [
      'Cranking your neck back to look up — keep it neutral',
      'Only lifting your upper body — your legs should come up too',
      'Rushing through reps — the hold at the top is where the work happens',
    ],
  },
  {
    slug: 'hyperextension',
    name: 'Hyperextension',
    title: 'How to Do Hyperextensions (Back Extensions Done Right)',
    description: 'Hyperextensions strengthen your lower back and glutes using a back extension bench. Learn proper range of motion and how to avoid pain.',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: ['back extension bench'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'EBui4Bt5N7o',
    intro: 'Hyperextensions (also called back extensions) strengthen your spinal erectors, glutes, and hamstrings. Despite the name, the goal isn\'t to hyperextend your spine — it\'s to extend your hips while keeping your back in a safe, neutral position. This makes it excellent for building a resilient lower back and preventing the back pain that plagues desk workers and lifters alike.',
    formCues: [
      'Set the pad at hip height so you can hinge freely',
      'Cross arms over your chest or hold a weight plate',
      'Hinge forward at the hips, lowering your torso toward the floor',
      'Stop when you feel a stretch in your hamstrings (about 90 degrees)',
      'Extend back up by squeezing your glutes — stop when your body is in a straight line',
    ],
    commonMistakes: [
      'Going past neutral (hyperextending) — stop when your body is straight, not arched',
      'Rounding your upper back — maintain a flat back throughout',
      'Using momentum to swing up — slow and controlled, squeeze glutes at the top',
    ],
  },

  // === COMPOUND (less searched, high value) ===
  {
    slug: 'pendlay-row',
    name: 'Pendlay Row',
    title: 'How to Do Pendlay Rows (Strict Barbell Row for Back Thickness)',
    description: 'The Pendlay row is a strict barbell row that starts from the floor each rep. Learn how it differs from bent-over rows and when to use it.',
    primaryMuscle: 'back',
    muscleGroups: ['back', 'biceps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    trackingMode: 'reps',
    aiTracked: false,
    videoId: 'tYxEGi7ir4I',
    intro: 'The Pendlay row is a stricter version of the barbell row, named after Olympic weightlifting coach Glenn Pendlay. Each rep starts from a dead stop on the floor — no momentum, no bouncing, no cheating. This makes it brutally honest: you either have the back strength to pull the weight, or you don\'t. It builds back thickness like nothing else.',
    formCues: [
      'Set up like a deadlift — bar over mid-foot, shoulder-width grip',
      'Hinge forward until your torso is nearly parallel to the floor',
      'Pull the bar explosively to your lower chest/upper abdomen',
      'Lower the bar back to the floor — let it come to a complete stop',
      'Reset your position before each rep — no touch-and-go',
    ],
    commonMistakes: [
      'Torso rising up during the pull — stay parallel to the floor',
      'Bouncing the bar off the floor — each rep is a dead stop',
      'Pulling to the belly instead of the lower chest — aim higher for better lat engagement',
    ],
  },
  {
    slug: 'barbell-thruster',
    name: 'Barbell Thruster',
    title: 'How to Do Barbell Thrusters (Full-Body Power Exercise)',
    description: 'Thrusters combine a front squat with an overhead press for a devastating full-body exercise. Learn proper technique and breathing.',
    primaryMuscle: 'quads',
    muscleGroups: ['quads', 'shoulders', 'glutes', 'core'],
    equipment: ['barbell'],
    difficulty: 'advanced',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'XvhRYWgekT4',
    intro: 'The thruster is a front squat that flows directly into an overhead press. It\'s one of the most metabolically demanding exercises — there\'s a reason CrossFit uses it in benchmark workouts like "Fran." It trains your quads, shoulders, core, and cardiovascular system simultaneously. If you want one exercise that does everything, this is it.',
    formCues: [
      'Clean the bar to a front rack position (bar on front delts)',
      'Squat to full depth while keeping elbows high and torso upright',
      'Drive out of the squat explosively',
      'Use the leg drive momentum to press the bar overhead',
      'Lower the bar back to front rack as you begin the next squat',
    ],
    commonMistakes: [
      'Pausing between the squat and press — it should be one fluid movement',
      'Pressing too early before the squat is finished — fully extend your legs first',
      'Elbows dropping in the front rack — keep them high to prevent the bar rolling forward',
    ],
  },
  {
    slug: 'cable-pull-through',
    name: 'Cable Pull-Through',
    title: 'How to Do Cable Pull-Throughs (Best Hip Hinge Teaching Tool)',
    description: 'Cable pull-throughs teach the hip hinge pattern better than any other exercise. Learn why trainers use them before deadlifts and kettlebell swings.',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: ['cable machine'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'dcHyetTdY_I',
    intro: 'The cable pull-through is the best exercise for learning the hip hinge — the movement pattern behind deadlifts, kettlebell swings, and Romanian deadlifts. The cable provides constant tension and a natural movement path that teaches your body exactly how a hip hinge should feel. If you struggle with "feeling" your glutes in other exercises, start here.',
    formCues: [
      'Set a cable to the lowest position with a rope attachment',
      'Stand facing away from the machine, straddling the cable',
      'Push your hips back while keeping your back flat — like closing a car door with your butt',
      'Let the cable pull between your legs until you feel a stretch in your hamstrings',
      'Squeeze your glutes to drive your hips forward to standing',
    ],
    commonMistakes: [
      'Squatting instead of hinging — push your butt BACK, don\'t bend your knees down',
      'Rounding your lower back — keep a flat back throughout the hinge',
      'Pulling with your arms — your arms are just hooks, the power comes from your glutes',
    ],
  },
  {
    slug: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    title: 'How to Do Kettlebell Swings (Proper Form + Common Mistakes)',
    description: 'Kettlebell swings build explosive hip power and torch calories. Learn the difference between Russian and American swings and proper hip hinge form.',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes', 'hamstrings', 'core'],
    equipment: ['kettlebell'],
    difficulty: 'intermediate',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'aSYap2yhW8s',
    intro: 'The kettlebell swing is a hip hinge, not a squat. That distinction matters because most people do it wrong — they squat the kettlebell up with their arms instead of snapping their hips to drive it. A proper kettlebell swing is one of the best exercises for building explosive hip power, posterior chain strength, and cardiovascular conditioning simultaneously.',
    formCues: [
      'Stand with feet shoulder-width apart, kettlebell a foot in front of you',
      'Hinge at the hips to grab the handle with both hands',
      'Hike the kettlebell back between your legs like a football snap',
      'Explosively drive your hips forward — the bell swings from hip power, not arms',
      'Let the bell float to chest height, then guide it back between your legs',
    ],
    commonMistakes: [
      'Squatting instead of hinging — your shins should stay nearly vertical',
      'Lifting with your arms — your arms are just ropes attached to the bell',
      'Leaning back at the top — stand tall and squeeze glutes, don\'t hyperextend',
    ],
  },

  // === FLEXIBILITY / MOBILITY (less competition, high search) ===
  {
    slug: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    title: 'How to Do the Hip Flexor Stretch (Release Tight Hips)',
    description: 'Tight hip flexors cause back pain, poor posture, and weak glutes. Learn the right way to stretch them and how long to hold.',
    primaryMuscle: 'hip flexors',
    muscleGroups: ['hip flexors', 'quads'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'hold',
    aiTracked: true,
    videoId: 'ktgtEWGhFd8',
    intro: 'If you sit for more than 4 hours a day, your hip flexors are tight. This isn\'t just a flexibility issue — tight hip flexors tilt your pelvis forward, compress your lower back, and inhibit your glutes from firing properly. The hip flexor stretch is one of the most important stretches for desk workers, runners, and anyone with lower back discomfort.',
    formCues: [
      'Kneel on one knee (back knee on a pad for comfort)',
      'Front foot flat on the floor with knee at 90 degrees',
      'Tuck your pelvis under — think "belt buckle toward chin"',
      'Lean forward slightly until you feel a deep stretch in the front of your back hip',
      'Hold for 30-60 seconds while breathing deeply',
    ],
    commonMistakes: [
      'Arching your lower back instead of tucking your pelvis — the tuck IS the stretch',
      'Leaning too far forward — you only need a slight lean with good pelvic position',
      'Holding your breath — breathe into the stretch to deepen it',
    ],
  },
  {
    slug: 'pigeon-pose',
    name: 'Pigeon Pose',
    title: 'How to Do Pigeon Pose (Deep Hip Opener for Tight Hips)',
    description: 'Pigeon pose opens your hip rotators and glutes. Learn how to do it without knee pain and modifications for tight hips.',
    primaryMuscle: 'glutes',
    muscleGroups: ['glutes', 'hip flexors'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'hold',
    aiTracked: true,
    videoId: 'AI5A1PRYX7E',
    intro: 'Pigeon pose is the deepest hip opener in most people\'s flexibility toolkit. It stretches the hip rotators, piriformis, and glutes — muscles that get incredibly tight from sitting and cause that deep ache in your butt and outer hip. It\'s also one of the most commonly modified poses because tight hips make the full version inaccessible for many people.',
    formCues: [
      'Start in a tabletop position on all fours',
      'Bring your right knee forward toward your right hand',
      'Angle your right shin as parallel to the front of your mat as your flexibility allows',
      'Extend your left leg straight back with top of the foot on the floor',
      'Sink your hips toward the floor and fold forward over your front leg',
    ],
    commonMistakes: [
      'Knee pain — use a rolled towel under your hip or keep your front shin at a sharper angle',
      'Hips uneven — use a block or pillow under the front hip to level your pelvis',
      'Forcing the front shin parallel — it\'s OK to keep it at an angle, flexibility comes with time',
    ],
  },
  {
    slug: 'worlds-greatest-stretch',
    name: 'World\'s Greatest Stretch',
    title: 'How to Do the World\'s Greatest Stretch (Full-Body Mobility)',
    description: 'The world\'s greatest stretch hits your hips, thoracic spine, hamstrings, and shoulders in one movement. Learn the complete sequence.',
    primaryMuscle: 'hip flexors',
    muscleGroups: ['hip flexors', 'hamstrings', 'shoulders', 'core'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: false,
    videoId: '7XheaZERvBQ',
    intro: 'It\'s called the world\'s greatest stretch for a reason. In one flowing sequence, it opens your hip flexors, stretches your hamstrings, mobilizes your thoracic spine, and activates your glutes. It\'s the single best warm-up movement you can do before any workout — and many strength coaches use it as the only warm-up drill their athletes need.',
    formCues: [
      'Step into a deep lunge with your right foot forward',
      'Place both hands on the floor inside your right foot',
      'Drop your left elbow toward the floor inside your right foot',
      'Rotate your right arm to the ceiling, opening your chest',
      'Return your hand to the floor and push your hips back to straighten your front leg (hamstring stretch)',
    ],
    commonMistakes: [
      'Rushing through the positions — hold each position for 2-3 breaths',
      'Skipping the thoracic rotation — the chest opening is the most valuable part',
      'Back knee on the ground — keep it hovering for extra core work',
    ],
  },

  // === ARMS / UPPER BODY (long-tail variations) ===
  {
    slug: 'skull-crusher',
    name: 'Skull Crusher',
    title: 'How to Do Skull Crushers (Tricep Exercise for Bigger Arms)',
    description: 'Skull crushers isolate all three tricep heads. Learn proper elbow position, bar path, and how to avoid the #1 mistake that wastes your reps.',
    primaryMuscle: 'triceps',
    muscleGroups: ['triceps'],
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'K3mFeNz4e3w',
    intro: 'Skull crushers (lying tricep extensions) are one of the best exercises for building tricep mass. Unlike pushdowns which emphasize the lateral head, skull crushers hit the long head of the triceps — the biggest head, and the one that gives your arms the most size. The name sounds scary, but with proper form, it\'s a perfectly safe and incredibly effective arm builder.',
    formCues: [
      'Lie on a flat bench holding an EZ bar or straight bar with a narrow grip',
      'Start with arms extended straight up, perpendicular to the floor',
      'Lower the bar toward your forehead by bending only at the elbows',
      'Keep your upper arms angled slightly back (toward your head, not straight up)',
      'Extend back to the starting position by straightening your elbows',
    ],
    commonMistakes: [
      'Elbows flaring out wide — keep them shoulder-width throughout',
      'Upper arms moving — only your forearms should move, upper arms stay fixed',
      'Lowering the bar to your nose/chin — aim for the forehead or just above for full range',
    ],
  },
  {
    slug: 'concentration-curl',
    name: 'Concentration Curl',
    title: 'How to Do Concentration Curls (Peak Bicep Contraction)',
    description: 'Concentration curls isolate the biceps with zero momentum. Learn the seated setup, proper bracing, and why Arnold loved this exercise.',
    primaryMuscle: 'biceps',
    muscleGroups: ['biceps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'TYrurDZTj9I',
    intro: 'The concentration curl is the highest bicep activation exercise according to ACE research. By bracing your elbow against your inner thigh, you eliminate every possible cheat — no swinging, no shoulder involvement, no momentum. It\'s just your bicep doing all the work. Arnold Schwarzenegger credited concentration curls as key to his legendary bicep peak.',
    formCues: [
      'Sit on a bench with legs spread, holding a dumbbell in one hand',
      'Brace the back of your upper arm against your inner thigh',
      'Start with the arm fully extended, palm facing forward',
      'Curl the weight up while keeping your upper arm completely still',
      'Squeeze at the top for a full second, then lower slowly',
    ],
    commonMistakes: [
      'Moving your upper arm — it should stay locked against your thigh',
      'Swinging the weight up — if you need momentum, the weight is too heavy',
      'Short range of motion — fully extend at the bottom and fully contract at the top',
    ],
  },
  {
    slug: 'arnold-press',
    name: 'Arnold Press',
    title: 'How to Do the Arnold Press (The Shoulder Press Upgrade)',
    description: 'The Arnold press hits all three deltoid heads in one movement. Learn the rotation technique and how it differs from a standard shoulder press.',
    primaryMuscle: 'shoulders',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: ['dumbbells'],
    difficulty: 'intermediate',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: '6K_N9AGhItQ',
    intro: 'The Arnold press — invented by Arnold Schwarzenegger himself — adds a rotation to the standard dumbbell press that hits all three heads of the deltoid in one movement. Regular presses mainly target the front and side delts, but the Arnold press rotation brings in the rear delts and increases time under tension. It\'s a more complete shoulder exercise in every way.',
    formCues: [
      'Sit with dumbbells at shoulder height, palms facing you (like the top of a curl)',
      'Press the weights up while rotating your palms to face forward',
      'At the top, your palms should face away from you — standard press position',
      'Reverse the movement on the way down — rotate palms back toward you',
      'The rotation should be smooth and continuous, not jerky',
    ],
    commonMistakes: [
      'Rotating too early or too late — the rotation should span the entire press',
      'Using too much weight — go lighter than your regular press, the rotation makes it harder',
      'Arching your back — keep your core tight and back against the seat',
    ],
  },
  {
    slug: 'good-morning',
    name: 'Good Morning',
    title: 'How to Do Good Mornings (Barbell Hip Hinge for Hamstrings)',
    description: 'Good mornings strengthen your hamstrings and lower back through a weighted hip hinge. Learn safe form and why they prevent back injuries.',
    primaryMuscle: 'hamstrings',
    muscleGroups: ['hamstrings', 'back', 'glutes'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    trackingMode: 'reps',
    aiTracked: false,
    videoId: '7cpldMZjLOs',
    intro: 'Good mornings are a barbell hip hinge that strengthens your entire posterior chain — hamstrings, glutes, and spinal erectors. They have an undeserved reputation as dangerous, but with proper form and appropriate weight, they\'re one of the best exercises for building a back that doesn\'t get hurt. Powerlifters use them specifically to strengthen the weak points in their deadlift and squat.',
    formCues: [
      'Place the barbell on your upper back (same position as a back squat)',
      'Stand with feet shoulder-width apart, slight bend in the knees',
      'Brace your core and push your hips back, hinging at the hips',
      'Lower until your torso is roughly parallel to the floor (or until hamstrings are tight)',
      'Drive your hips forward to return to standing, squeezing glutes at the top',
    ],
    commonMistakes: [
      'Rounding your back — keep your back flat and chest proud throughout',
      'Going too heavy too soon — start with just the bar and build up slowly',
      'Bending your knees too much — this should be a hinge, not a squat',
    ],
  },
  {
    slug: 'turkish-get-up',
    name: 'Turkish Get-Up',
    title: 'How to Do the Turkish Get-Up (Full-Body Strength in One Move)',
    description: 'The Turkish get-up builds total body strength, stability, and mobility in one complex movement. Learn the 7-step sequence from floor to standing.',
    primaryMuscle: 'core',
    muscleGroups: ['core', 'shoulders', 'glutes', 'quads'],
    equipment: ['kettlebell'],
    difficulty: 'advanced',
    trackingMode: 'reps',
    aiTracked: false,
    videoId: 'g5dwOlGGfmU',
    intro: 'The Turkish get-up is the most complete single exercise in fitness. Getting from lying on the floor to standing while holding a weight overhead requires strength, stability, mobility, and coordination from every joint in your body. It\'s been used for centuries by wrestlers, martial artists, and strongmen. One rep takes 30-45 seconds. Five reps per side is a serious workout.',
    formCues: [
      'Lie on your back holding a kettlebell in one hand, arm locked out overhead',
      'Bend the knee on the same side as the kettlebell, foot flat on the floor',
      'Roll to your opposite elbow, then to your hand, keeping the weight up',
      'Bridge your hips up and sweep your straight leg underneath you to a kneeling position',
      'Stand up from the lunge position, weight still locked out overhead',
    ],
    commonMistakes: [
      'Taking your eyes off the weight — always watch the kettlebell',
      'Rushing through the steps — each position is a checkpoint, not a speed drill',
      'Starting too heavy — learn the movement with no weight, then a shoe balanced on your fist',
    ],
  },

  // === WALL SIT / SQUAT HOLD ===
  {
    slug: 'wall-sit',
    name: 'Wall Sit',
    title: 'How to Do Wall Sits (Build Quad Endurance Anywhere)',
    description: 'Wall sits build quad endurance and mental toughness with zero equipment. Learn proper position, how long to hold, and progressions.',
    primaryMuscle: 'quads',
    muscleGroups: ['quads', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'hold',
    aiTracked: true,
    videoId: 'S_SmgeQ7hiU',
    intro: 'The wall sit is deceptively simple and devastatingly effective. You sit against a wall with your thighs parallel to the floor and... hold. That\'s it. Within 30 seconds, your quads will be on fire. Within 60 seconds, you\'ll question your life choices. It\'s one of the best exercises for building quad endurance, and it requires absolutely nothing except a wall.',
    formCues: [
      'Stand with your back flat against a wall',
      'Slide down until your thighs are parallel to the floor (90-degree knee bend)',
      'Feet shoulder-width apart, about 2 feet from the wall',
      'Keep your back flat against the wall — no arching',
      'Hold while breathing steadily — don\'t hold your breath',
    ],
    commonMistakes: [
      'Thighs not reaching parallel — if you\'re above 90 degrees, slide lower',
      'Knees past your toes — move feet further from the wall',
      'Hands on thighs for support — cross arms over your chest to keep it honest',
    ],
  },
  {
    slug: 'sumo-squat',
    name: 'Sumo Squat',
    title: 'How to Do Sumo Squats (Wide-Stance Inner Thigh Builder)',
    description: 'Sumo squats target your inner thighs and glutes with a wide stance. Learn proper foot angle, depth, and how they differ from regular squats.',
    primaryMuscle: 'quads',
    muscleGroups: ['quads', 'glutes', 'adductors'],
    equipment: ['none'],
    difficulty: 'beginner',
    trackingMode: 'reps',
    aiTracked: true,
    videoId: 'ihvHG1QH654',
    intro: 'The sumo squat uses a wider stance with toes pointed out, shifting emphasis to your inner thighs (adductors) and glutes. It\'s named after the stance sumo wrestlers use, and it\'s one of the best bodyweight exercises for the muscles that regular squats don\'t hit hard enough. If you want balanced leg development, sumo squats fill the gap.',
    formCues: [
      'Stand with feet wide — about 1.5x shoulder-width',
      'Point toes out at 45 degrees',
      'Squat straight down, keeping your torso as upright as possible',
      'Push your knees out over your toes as you descend',
      'Drive through your heels to stand, squeezing inner thighs and glutes at the top',
    ],
    commonMistakes: [
      'Knees collapsing inward — actively push them out over your toes',
      'Leaning forward — sumo squats should be more upright than regular squats',
      'Not going deep enough — aim for thighs parallel or below',
    ],
  },
]

/**
 * Get exercise by slug
 */
export function getExercise(slug) {
  return exercises.find(e => e.slug === slug) || null
}

/**
 * Get exercises grouped by primary muscle
 */
export function getExercisesByMuscle() {
  const groups = {}
  for (const ex of exercises) {
    const muscle = ex.primaryMuscle
    if (!groups[muscle]) groups[muscle] = []
    groups[muscle].push(ex)
  }
  return groups
}
